Add missing limits.h include to fix undeclared INT_MAX
Fixes:

```
visit_il.c: In function ‘struct_entry_list_push_back’:
visit_il.c:90:20: error: ‘INT_MAX’ undeclared (first use in this function)
   90 |     if (p->size == INT_MAX)
      |                    ^~~~~~~
visit_il.c:29:1: note: ‘INT_MAX’ is defined in header ‘<limits.h>’; this is probably fixable by adding ‘#include <limits.h>’

```